# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_predM1_rcpp <- function(cy, k, e, ie) {
    .Call(`_mgpr_compute_predM1_rcpp`, cy, k, e, ie)
}

